### ISSUE TITLE
Instalación

### ISSUE THREAD

**Issue by edejuan** [Oneirag/commodity_data#4]
Hola @Oneirag , 
Enhorabuena por tu código, tiene una pinta estupenda, aunque me temo que soy novato en Python y no sé bien cómo instalarlo. 
Suelo tirar de "pip", por lo que no sé cómo hacer para correr tu código. 
He conseguido hacer funcionar OMIEData, una librería que está por aquí en Github, muy chula para precios de OMIE. Sin embargo no tiene OMIP, y me gustaría cacharrear con los datos de OMIP. 
Para que veas que soy un novato, uso Google Colab... 
Cómo podría hacer para correr tu código? 
Gracias y perdona que lo ponga como "Issue", pero no sé cómo mandar mensajes directos en Github. 
Un abrazo, 
Quique

**Comment by Oneirag** [comment]
Gracias @edejuan 
A ver si saco un rato y pongo una guía de instalación. En principio no es mucho más que hacer un `pip install git+https://github.com/Oneirag/commodity_data.git` y a partir de ahí con importar la librería tiraría. Lo malo es que hay que generar unos ficheros de configuración para ubicar dónde se dejan los datos.
No lo he probado en google colab, pero funcionar, funcionar, funcionará. Lo que pasa es que con google colab es un poco rollo hacer los datos persistentes: tienes que montar manualmente tu disco de google drive, crear ficheros de configuración, cambiar alguna configuración para que apunte al disco de google drive, etc. Igual tengo que cambiar un poco la librería ong_utils para que funcione bien ahí. Realmente lo que pasa es que me hago las librerías para mi y lo uso en las máquinas de casa y claro pueden pasar estas cosas al usar otro entorno así que te lo agradezco ;)
Y sobre la información de omie, yo la saco de una forma un poco indirecta: uso las apis de esios (https://api.esios.ree.es/), hay que solicitar un token y "a jugar". Esios tiene la mayor parte de la info de omie más otras (por ejemplo, el precio PVPC, los precios de los desvíos, los P48...), tengo otra librería para los datos de esios (no todos porque hay tanto)
Pues nada, lo pruebo en google colab a ver.
Gracias!!!

**Comment by Oneirag** [comment]
Hola @edejuan 
De nuevo: gracias. Me has ayudado a encontrar algunos bugs que tenía. Ya lo he probado en google colab y funciona, he subido esta versión #5 que además tiene en los comentarios explicado cómo hacerlo funcionar en colab (que tenía truco).
Si no te funciona o algo me dices

**Comment by edejuan** [comment]
Gracias a tí Oscar por compartir! 
Vaya currada de documentación! 
Le echaré un ojo con calma, ya te digo que soy principiante y voy poco a poco. Estoy aprendiendo mucho con tu código. 
Tiene una pinta estupenda. 
Gracias otra vez
Un abrazo
